services:
  flask-app:
    image: localhost:5001/flask-app-dev:latest
    ports:
      - "5000:5000"
    volumes:
      - data:/app
      - /app/templates
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      #placement:
      #  max_replicas_per_node: 1 
      update_config:
        parallelism: 2        
        delay: 10s           
      rollback_config:
        parallelism: 1

volumes:
  data:
