---
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: >
        external_url "http://192.168.15.145:8929"
    ports:
      - 8929:8929
      - 443:443
      - 64502:22
    volumes:
      - data:/var/opt/gitlab
      - config_gitlab:/etc/gitlab
      - logs:/var/log/gitlab
    networks:
      - gitlab

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/projet-git/.ssh:/var/jenkins_home/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    networks:
      - gitlab

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - 9000:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqubedata:/opt/sonarqube/data
      - sonarqubeextensions:/opt/sonarqube/extensions
      - sonarqubelogs:/opt/sonarqube/logs
      - sonarqubetemp:/opt/sonarqube/temp
    networks:
      - gitlab

  sonar-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    networks:
      - gitlab

volumes:
  data: 
  config_gitlab:
  logs:
  jenkins_home:
  sonarqubedata:
  sonarqubeextensions: 
  sonarqubelogs:
  sonarqubetemp:
  postgresqldata:

networks:
  gitlab:
