---
services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"  # Traefik écoute sur le port 80 pour rediriger le trafic HTTP
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik-localhost.fr`)"
      - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - gitlab 

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab-localhost.fr`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    ports:
      - 64502:22
    volumes:
      - data:/var/opt/gitlab
      - config_gitlab:/etc/gitlab
      - logs:/var/log/gitlab
    networks:
      - gitlab

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    user: "1000:999"
    container_name: jenkins
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins-localhost.fr`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/projet-git/.ssh:/var/jenkins_home/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    networks:
      - gitlab

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube-localhost.fr`)"
      - "traefik.http.services.sonarqube.loadbalancer.server.port=9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqubedata:/opt/sonarqube/data
      - sonarqubeextensions:/opt/sonarqube/extensions
      - sonarqubelogs:/opt/sonarqube/logs
      - sonarqubetemp:/opt/sonarqube/temp
    networks:
      - gitlab

  sonar-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    networks:
      - gitlab

volumes:
  data: 
  config_gitlab:
  logs:
  jenkins_home:
  sonarqubedata:
  sonarqubeextensions: 
  sonarqubelogs:
  sonarqubetemp:
  postgresqldata:

networks:
  gitlab:
